on: [push, workflow_dispatch]

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Create PDF document
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make PDF file
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        latexmk_shell_escape: true
    - name: Store PDF
      uses: actions/upload-artifact@v3.1.2
      with:
        path: main.pdf
